[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter = "GzAkiWUe58KgD9S7LwefX3UHuaMka5GcGNvPzdckQdAr"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
